### ISSUE TITLE
Submissions page milestone

### ISSUE THREAD

**Issue by cl8n** [cl8n/project-loved-web#49]
tracking here everything that should be added to submissions page before it's considered "ready" to replace all of the old stuff.

view
- [x] ability to show/hide any of the stats columns
- [x] #39, maybe allow choosing a second sort too, either way there should be sane defaults for second sort
- [x] #37
- [x] ~~show +X for guest creators in Mapper column~~ nevermind cuz nobody will fill this data in in the first place
- [x] page to view separate table for maps that are now loved or ranked
- [x] separate status for "in voting", "failed voting"
- [x] source more translations for Submissions / Submit a map
      good enough and I'll ask around once i add more features to the translations page.
- [x] experiment with alternate ways to expand rows other than that text button off to the side
      unfortunately quite a challenge to build intuitive interactions/styling on rows due to DOM's special handling of tr.
- [x] ~~second pass over styling in general, hopefully with more feedback by the time this can happen~~ nobody really had any further style suggestions

function
- [x] reject new submissions for loved/ranked maps
- [x] #36
- [x] some way for a captain (or huu probably) to definitively reject a map for concrete reason e.g. going for ranked or mapper requested it to be removed
      may not be necessary, since the priority sorting is supposed to naturally send these to the bottom.
- [x] ~~the captains-reviews part of #3~~
      ~~necessary at this time only if captains have a hard time finding what needs their review (red bold button)~~
      captains seem to be doing fine without this for now
- [x] some ultra primitive way to routinely update beatmap data pending connection to tracker

data
- [x] #9 for results-dependent display
- [ ] #7

**Comment by cl8n** [comment]
good enough
